all: build.o

build.o: clean_autogenerated_files.o flutter_build.o lint_code.o  format_code.o

# Flutter

flutter_build.o:
	flutter clean
	flutter pub get
	flutter packages pub run build_runner build --delete-conflicting-outputs --verbose


# Dart linter
lint_code.o:
	flutter analyze

# Dart formatter

format_code.o:
	dart format lib

# Clean

clean_autogenerated_files.o:
	# find lib/data_layer/entities . -name '*.g.dart' -type f -delete
	# find lib/data_layer/entities . -name '*.freezed.dart' -type f -delete
	find test . -name '*.mocks.dart' -type f -delete
	rm -rf lib/gen
